name: Pull Request Validation

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Debug changed files
        run: |
          echo "${{ steps.changed-files.outputs.files }}"
      - run: npm install

      - name: Create Cocos tsconfig stub
        run: |
          mkdir -p temp
          echo '{
            "compilerOptions": {
              "target": "ES6",
              "module": "commonjs",
              "moduleResolution": "node"
            }
          }' > temp/tsconfig.cocos.json

      - run: npm run validate
        env:
          BRANCH_NAME: ${{ github.head_ref }}
          PR_TITLE: ${{ github.event.pull_request.title }}