name: lint code

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get changed files
        id: changed-files
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only --diff-filter=ACMR origin/main...HEAD >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Debug changed files
        run: |
          echo "===== CHANGED FILES ====="
          echo "${{ steps.changed-files.outputs.files }}"
          echo "========================="

      - name: Run ESLint on changed lines only
        run: node tools/validation/src/lint-changed-line.ts