name: Validate Branch Name

on:
    pull_request:
        branches:
            - main
            - develop

jobs:
    branch-name:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npm run validate:branch-name
              env:
                  BRANCH_NAME: ${{ github.head_ref }}
